### ISSUE TITLE
Warning: "No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred."

### ISSUE THREAD

**Issue by anirudhkhanna-oyo** [apvarun/parcel-plugin-prettier#3]
When added to parcel project, it is throwing this warning:

"No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred."

**Comment by prasadmes** [comment]
Facing the same issue here
ANy solutions?

**Comment by apvarun** [comment]
Fixed in version v0.2.1
